
apiVersion: v1
kind: Namespace
metadata:
  name: twodut-sonic2
---
apiVersion: networkop.co.uk/v1beta1
kind: Topology
metadata:
  name: sonic2
  namespace: twodut-sonic2
spec:
  links:
  - local_intf: eth1
    local_ip: ""
    peer_intf: eth1
    peer_ip: ""
    peer_pod: sonic
    uid: 0
  - local_intf: eth2
    local_ip: ""
    peer_intf: eth2
    peer_ip: ""
    peer_pod: sonic
    uid: 1
  - local_intf: eth3
    local_ip: ""
    peer_intf: eth3
    peer_ip: ""
    peer_pod: sonic
    uid: 2
  - local_intf: eth4
    local_ip: ""
    peer_intf: eth4
    peer_ip: ""
    peer_pod: sonic
    uid: 3
---
apiVersion: networkop.co.uk/v1beta1
kind: Topology
metadata:
  name: sonic
  namespace: twodut-sonic2
spec:
  links:
  - local_intf: eth1
    local_ip: ""
    peer_intf: eth1
    peer_ip: ""
    peer_pod: sonic2
    uid: 0
  - local_intf: eth2
    local_ip: ""
    peer_intf: eth2
    peer_ip: ""
    peer_pod: sonic2
    uid: 1
  - local_intf: eth3
    local_ip: ""
    peer_intf: eth3
    peer_ip: ""
    peer_pod: sonic2
    uid: 2
  - local_intf: eth4
    local_ip: ""
    peer_intf: eth4
    peer_ip: ""
    peer_pod: sonic2
    uid: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    pod: sonic
  name: service-sonic
  namespace: twodut-sonic2
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: gnmi
    port: 9339
    protocol: TCP
    targetPort: 9339
  - name: p4rt
    port: 9559
    protocol: TCP
    targetPort: 9559
  selector:
    app: sonic
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sonic
    topo: twodut-sonic2
  name: sonic
  namespace: twodut-sonic2
spec:
  containers:
  - command:
    - go
    - run
    - main.go
    image: sonic-vs:latest
    imagePullPolicy: IfNotPresent
    name: sonic
    securityContext:
      privileged: true
  - name: lucius
    command:
    - /lucius/lucius
    - -alsologtostderr
    image: us-west1-docker.pkg.dev/openconfig-lemming/release/lucius:ga
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
  initContainers:
  - args:
    - "5"
    - "0"
    image: us-west1-docker.pkg.dev/kne-external/kne/networkop/init-wait:ga
    imagePullPolicy: IfNotPresent
    name: init-sonic
    resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    pod: sonic2
  name: service-sonic2
  namespace: twodut-sonic2
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: gnmi
    port: 9339
    protocol: TCP
    targetPort: 9339
  - name: p4rt
    port: 9559
    protocol: TCP
    targetPort: 9559
  selector:
    app: sonic2
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sonic2
    topo: twodut-sonic2
  name: sonic2
  namespace: twodut-sonic2
spec:
  containers:
  - command:
    - go
    - run
    - main.go
    image: sonic-vs:latest
    imagePullPolicy: IfNotPresent
    name: sonic
    securityContext:
      privileged: true
  - name: lucius
    command:
    - /lucius/lucius
    - -alsologtostderr
    image: us-west1-docker.pkg.dev/openconfig-lemming/release/lucius:ga
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
  initContainers:
  - args:
    - "5"
    - "0"
    image: us-west1-docker.pkg.dev/kne-external/kne/networkop/init-wait:ga
    imagePullPolicy: IfNotPresent
    name: init-sonic
    resources: {}